#!/bin/bash

if [ $# -eq 0 ]
then
	unset {http_proxy,https_proxy,ftp_proxy,no_proxy,HTTP_PROXY,HTTPS_PROXY}
	echo "" > /home/alvi/.gnupg/dirmngr.conf
	echo "connessione riportata alla configurazione standard"
	if [ -e /etc/apt/apt.conf.d/apt.conf ]
	then
		mv /etc/apt/apt.conf.d/apt.conf /home/alvi/Documents/script/cambiaConnessione/
		killall dirmngr
	else
		echo "non è stato trovato il file /etc/apt/apt.conf.d/apt.conf"
	fi

elif [ $1 = castelli -o $1 = Castelli ]
then
	export {http_proxy,https_proxy,ftp_proxy,HTTP_PROXY,HTTPS_PROXY}="http://127.0.0.1:3128"
	export no_proxy="localhost,127.0.0.1"
	echo http-proxy=http://127.0.0.1:3128 > /home/alvi/.gnupg/dirmngr.conf 	
	echo "connesione configurata per operare all'interno del ISS Castelli"
	if [ -e /home/alvi/Documents/script/cambiaConnessione/apt.conf ]
	then
		mv /home/alvi/Documents/script/cambiaConnessione/apt.conf /etc/apt/apt.conf.d/
		killall dirmngr
	else
		echo "non è stato trovato il file /home/alvi/Documents/script/cambiaConnessione/apt.conf"
	fi
fi

